# Global "top-level" compose file.
# Imports all compose files for individual services.
#
# This structure allows for global variables in the top-level .env to be
# consumed by each service, while still having separation of services into
# distinct compose.yaml files.
---
name: homelab
include:
  - path: services/caddy.yaml
  - path: services/speedtest.yaml
  - path: services/downloadarr.yaml
  - path: services/jelly.yaml
