---
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - path: ${SECRETS_PATH}/gluetun.env
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - TZ=${SERVER_TZ}
      - UPDATER_PERIOD=24h
  
  gluetun-speedtest-tracker:
    container_name: gluetun-speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - APP_TIMEZONE=${SERVER_TZ}
      - DB_CONNECTION=sqlite
      - PUBLIC_DASHBOARD=true
      - SPEEDTEST_SCHEDULE="0 * * * *"  # every hour, every day, on the hour.
      - DISPLAY_TIMEZONE=${SERVER_TZ}
      - PRUNE_RESULTS_OLDER_THAN=92
    env_file: 
      - path: ${SECRETS_PATH}/gluetun-speedtest-tracker.env
    volumes:
      - ${SERVER_CONFIG_PATH}/gluetun-speedtest-tracker:/config
