---
services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
    # Open up port per service as per Caddyfile
      - 80:80
      - 81:81
    # Defaults once I have HTTPS
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${SERVER_CONFIG_PATH}/caddy/site:/srv
      - ${SERVER_CONFIG_PATH}/caddy/data:/data
      - ${SERVER_CONFIG_PATH}/caddy/config:/config