---
services:
  caddy:
    container_name: caddy
    image: serfriz/caddy-duckdns:latest
    restart: unless-stopped
    env_file: 
      - path: ${SECRETS_PATH}/caddy.env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${SERVER_CONFIG_PATH}/caddy/site:/srv
      - ${SERVER_CONFIG_PATH}/caddy/data:/data
      - ${SERVER_CONFIG_PATH}/caddy/config:/config