---
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - ${SERVER_CONFIG_PATH}/jellyfin/config:/config
      - ${SERVER_CONFIG_PATH}/jellyfin/cache:/cache
      - type: bind
        source: ${SERVER_DATA_PATH}/media
        target: /media

  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${SERVER_TZ}
    volumes:
      - ${SERVER_CONFIG_PATH}/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3