---
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - ${SERVER_CONFIG_PATH}/jellyfin/config:/config
      - ${SERVER_CONFIG_PATH}/jellyfin/cache:/cache
      - type: bind
        source: ${SERVER_DATA_PATH}/media
        target: /media

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${SERVER_TZ}
    volumes:
      - ${SERVER_CONFIG_PATH}/jellyseerr:/app/config