---
services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: unless-stopped
    environment:
      MODE: standalone
      TITLE: PandaSpeed
      TELEMETRY: true
    ports:
      - 80:80 # webport mapping (host:container)
    env_file: 
      - path: ./secrets/speedtest.env
    volumes:
      - ${SERVER_CONFIG_PATH}/librespeed:/database
