---
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - APP_TIMEZONE=${SERVER_TZ}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 8,12,18 * * *"  # 8 AM, noon, and 6 PM every day 
      - DISPLAY_TIMEZONE=${SERVER_TZ}  # optional
      - PRUNE_RESULTS_OLDER_THAN=92  # optional
    env_file: 
      - path: ./secrets/speedtest-tracker.env
    ports:
      - 81:80 # webport mapping (host:container)
    volumes:
      - ${SERVER_CONFIG_PATH}/speedtest-tracker:/config

  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: unless-stopped
    environment:
      MODE: standalone
      TITLE: PandaSpeed
      TELEMETRY: true
    env_file: 
      - path: ./secrets/speedtest.env
    ports:
      - 80:80  # webport mapping (host:container)
    volumes:
      - ${SERVER_CONFIG_PATH}/librespeed:/database
