---
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - APP_TIMEZONE=${SERVER_TZ}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 * * * *"  # every hour, every day, on the hour.
      - DISPLAY_TIMEZONE=${SERVER_TZ}  # optional
      - PRUNE_RESULTS_OLDER_THAN=92  # optional
    env_file: 
      - path: ${SECRETS_PATH}/speedtest-tracker.env
    volumes:
      - ${SERVER_CONFIG_PATH}/speedtest-tracker:/config

  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: unless-stopped
    environment:
      MODE: standalone
      TITLE: PandaSpeed
      TELEMETRY: true
    env_file: 
      - path: ${SECRETS_PATH}/speedtest.env
    volumes:
      - ${SERVER_CONFIG_PATH}/librespeed:/database
